config/routes.rb
Rails.application.routes.draw do
  
  resources :companies
  resources :book_resources
  resources :resources
  resources :quotes
  Shrine.plugin :upload_endpoint

  resources :content_fields
  post 'alerts/reply'

  resource :alerts do
    collection do
      post 'reply'
      post 'create_alert'
    end
  end

  resources :images, only: [:new, :create, :index, :edit, :update]
  resources :resource_requests, only: [:create]

  get "/bios/meet_us" => "bios#meet_us"
  
  # resources :notification_preferences
  resources :group_messages
  resources :groups
  resources :group_memberships
  resources :admin_messages
  resources :plans
  resources :mentorships
  resources :messages
  resources :bio_questions
  resources :bio_answers
  resources :bios
  resources :resources
  resources :resource_types
  resources :book_resources
  resources :user_emailer

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'registrations'}

  root to: "dashboard#view"
  mount ImageUploader.upload_endpoint(:cache) => "/images/upload"

  # post "user_emailer/send_book_resources/:email" => "user_emailer"

  post "/assign_company_id/:target_user_id/:company_id" => "dashboard#super_admin_assign_company_id_to_new_user"
  get "company_admin_login/:company_id" => "dashboard#super_admin_log_into_company"

  get "/images/index" => "images#index"

  get "/notification_preferences" => "notification_preferences#index"
  post '/notification_preferences/enable_notification/:reason/:type' => 'notification_preferences#enable_notification'
  post '/notification_preferences/disable_notification/:reason/:type' => 'notification_preferences#disable_notification'

  post '/twilio/voice' => 'twilio#voice'

  get "/alerts/send_email" => "alerts#send_email"
  post "/alerts/send_notifications/:event/:createdModelId" => "alerts#send_notifications"

  get "/landing_page" => "admin_messages#landing_page"
  get "/download_book_resources" => "admin_messages#download_book_resources"
  get "/blog" => "home#blog"
  get "/test" => "home#test"

  get "/user/dashboard" => "dashboard#view"
  get "/user/dashboard/:active_user_id" => "dashboard#view"
  get "/user/group-dashboard" => "dashboard#group_view"
  get "/user/group-dashboard/:active_group_id" => "dashboard#group_view"

  get "/toggle_coach/:target_user_id" => "dashboard#admin_toggle_coach_permissions"
  get "/toggle_admin/:target_user_id" => "dashboard#admin_toggle_admin_permissions"
  get "/toggle_active/:target_user_id" => "dashboard#admin_toggle_active"
  get "/toggle_deleted/:target_user_id" => "dashboard#admin_toggle_deleted"
  get "/activate_user/:target_user_id" => "dashboard#admin_activate_user"

  get "/" => "dashboard#view"


end

app/models/admin_message.rb
class AdminMessage < ActiveRecord::Base
end

app/models/alert.rb
class Alert < ActiveRecord::Base
end

app/models/bio.rb
class Bio < ActiveRecord::Base
end

app/models/bio_answer.rb
class BioAnswer < ActiveRecord::Base
end

app/models/bio_question.rb
class BioQuestion < ActiveRecord::Base
end

app/models/book_resource.rb
class BookResource < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/content_field.rb
class ContentField < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base

	require "shrine/storage/s3"

	# adds an `image` virtual attribute
	include ImageUploader::Attachment.new(:image)

end

app/models/mentorship.rb
class Mentorship < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/resource_type.rb
class ResourceType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # before_save :set_default_permissions
  scope :ordered_by_name, -> { order(first_name: :asc) }

  def full_name
    "#{first_name} #{last_name}"
  end

   def set_default_permissions

    # TODO: needs debugging:
      self.is_a_coach = false
      self.is_an_admin = false
      self.is_super_admin = false
   end    
  
  # ensure user account is active  
  def active_for_authentication?  
    self.is_active  
  end  
  
end

app/controllers/group_messages_controller.rb
class GroupMessagesController < ApplicationController
  before_action :set_group_message, only: [:show, :edit, :update, :destroy]

  # GET /group_messages
  def index
    @group_messages = GroupMessage.all
  end

  # GET /group_messages/1
  def show
  end

  # GET /group_messages/new
  def new
    @group_message = GroupMessage.new
  end

  # GET /group_messages/1/edit
  def edit
  end

  # POST /group_messages
  def create
    @group_message = GroupMessage.new(group_message_params)

    if @group_message.save
      redirect_to "/user/group-dashboard/#{@group_message.group_id}", notice: 'Group message was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /group_messages/1
  def update
    if @group_message.update(group_message_params)
      redirect_to "/user/group-dashboard/#{@group_message.group_id}", notice: 'Group message was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /group_messages/1
  def destroy
    @group_message.destroy
    redirect_to "/group/dashboard/#{@group_message.group_id}", notice: 'Group message was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_message
      @group_message = GroupMessage.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_message_params
      params.require(:group_message).permit(:group_id, :from, :content)
    end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/group_messages/_form.html.erb
<%= form_for(@group_message) do |f| %>
  <% if @group_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_message.errors.count, "error") %> prohibited this group_message from being saved:</h2>

      <ul>
      <% @group_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="hide-this">
      <%= f.number_field :group_id, :value => @active_group_id  %>

      <%= f.number_field :from, :value => @active_user_id  %>
  </div>

  <div class="field">
    <% f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_messages/edit.html.erb
<h1>Editing Group Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_message %> |
<%= link_to 'Back', group_messages_path %>

app/views/group_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Group Messages</h1>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>From</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_messages.each do |group_message| %>
      <tr>
        <td><%= group_message.group_id %></td>
        <td><%= group_message.from %></td>
        <td><%= group_message.content %></td>
        <td><%= link_to 'Show', group_message %></td>
        <td><%= link_to 'Edit', edit_group_message_path(group_message) %></td>
        <td><%= link_to 'Destroy', group_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group message', new_group_message_path %>

app/views/group_messages/new.html.erb
<%= render "group_messages/form" %> 

app/views/group_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @group_message.group_id %>
</p>

<p>
  <strong>From:</strong>
  <%= @group_message.from %>
</p>

<p>
  <strong>Content:</strong>
  <%= @group_message.content %>
</p>

<%= link_to 'Edit', edit_group_message_path(@group_message) %> |
<%= link_to 'Back', group_messages_path %>