config/routes.rb
Rails.application.routes.draw do
  
  resources :companies
  resources :book_resources
  resources :resources
  resources :quotes
  Shrine.plugin :upload_endpoint

  resources :content_fields
  post 'alerts/reply'

  resource :alerts do
    collection do
      post 'reply'
      post 'create_alert'
    end
  end

  resources :images, only: [:new, :create, :index, :edit, :update]
  resources :resource_requests, only: [:create]

  get "/bios/meet_us" => "bios#meet_us"
  
  # resources :notification_preferences
  resources :group_messages
  resources :groups
  resources :group_memberships
  resources :admin_messages
  resources :plans
  resources :mentorships
  resources :messages
  resources :bio_questions
  resources :bio_answers
  resources :bios
  resources :resources
  resources :resource_types
  resources :book_resources
  resources :user_emailer

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'registrations'}

  root to: "dashboard#view"
  mount ImageUploader.upload_endpoint(:cache) => "/images/upload"

  # post "user_emailer/send_book_resources/:email" => "user_emailer"

  post "/assign_company_id/:target_user_id/:company_id" => "dashboard#super_admin_assign_company_id_to_new_user"
  get "company_admin_login/:company_id" => "dashboard#super_admin_log_into_company"

  get "/images/index" => "images#index"

  get "/notification_preferences" => "notification_preferences#index"
  post '/notification_preferences/enable_notification/:reason/:type' => 'notification_preferences#enable_notification'
  post '/notification_preferences/disable_notification/:reason/:type' => 'notification_preferences#disable_notification'

  post '/twilio/voice' => 'twilio#voice'

  get "/alerts/send_email" => "alerts#send_email"
  post "/alerts/send_notifications/:event/:createdModelId" => "alerts#send_notifications"

  get "/landing_page" => "admin_messages#landing_page"
  get "/download_book_resources" => "admin_messages#download_book_resources"
  get "/blog" => "home#blog"
  get "/test" => "home#test"

  get "/user/dashboard" => "dashboard#view"
  get "/user/dashboard/:active_user_id" => "dashboard#view"
  get "/user/group-dashboard" => "dashboard#group_view"
  get "/user/group-dashboard/:active_group_id" => "dashboard#group_view"

  get "/toggle_coach/:target_user_id" => "dashboard#admin_toggle_coach_permissions"
  get "/toggle_admin/:target_user_id" => "dashboard#admin_toggle_admin_permissions"
  get "/toggle_active/:target_user_id" => "dashboard#admin_toggle_active"
  get "/toggle_deleted/:target_user_id" => "dashboard#admin_toggle_deleted"
  get "/activate_user/:target_user_id" => "dashboard#admin_activate_user"

  get "/" => "dashboard#view"


end

app/models/admin_message.rb
class AdminMessage < ActiveRecord::Base
end

app/models/alert.rb
class Alert < ActiveRecord::Base
end

app/models/bio.rb
class Bio < ActiveRecord::Base
end

app/models/bio_answer.rb
class BioAnswer < ActiveRecord::Base
end

app/models/bio_question.rb
class BioQuestion < ActiveRecord::Base
end

app/models/book_resource.rb
class BookResource < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/content_field.rb
class ContentField < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base

	require "shrine/storage/s3"

	# adds an `image` virtual attribute
	include ImageUploader::Attachment.new(:image)

end

app/models/mentorship.rb
class Mentorship < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/resource_type.rb
class ResourceType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # before_save :set_default_permissions
  scope :ordered_by_name, -> { order(first_name: :asc) }

  def full_name
    "#{first_name} #{last_name}"
  end

   def set_default_permissions

    # TODO: needs debugging:
      self.is_a_coach = false
      self.is_an_admin = false
      self.is_super_admin = false
   end    
  
  # ensure user account is active  
  def active_for_authentication?  
    self.is_active  
  end  
  
end

app/controllers/bio_questions_controller.rb
class BioQuestionsController < ApplicationController
  before_action :set_bio_question, only: [:show, :edit, :update, :destroy]
  before_filter :admin_user, only: [:index, :show, :edit, :update, :destroy]

  layout "signed-in"

  # GET /bio_questions
  def index
    @bio_questions = BioQuestion.all
  end

  # GET /bio_questions/1
  def show
  end

  # GET /bio_questions/new
  def new
    @bio_question = BioQuestion.new
  end

  # GET /bio_questions/1/edit
  def edit
  end

  # POST /bio_questions
  def create
    @bio_question = BioQuestion.new()
    @bio_question.question_text = bio_question_params["question_text"]
    @bio_question.question_order_by = 0
    @bio_question.active = false

    if @bio_question.save
      redirect_to @bio_question, notice: 'Bio question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bio_questions/1
  def update
    if @bio_question.update(bio_question_params)
      redirect_to @bio_question, notice: 'Bio question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bio_questions/1
  def destroy
    @bio_question.destroy
    redirect_to bio_questions_url, notice: 'Bio question was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bio_question
      @bio_question = BioQuestion.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def bio_question_params
      params.require(:bio_question).permit(:question_text, :question_order_by, :active)
    end

    def admin_user
      redirect_to "/" unless current_user.is_an_admin?
    end
end

app/helpers/bio_questions_helper.rb
module BioQuestionsHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/bio_questions/_form.html.erb
<%= form_for(@bio_question) do |f| %>
  <% if @bio_question.errors.any? %> 
    <div id="error_explanation">
      <h2><%= pluralize(@bio_question.errors.count, "error") %> prohibited this bio_question from being saved:</h2>

      <ul>
      <% @bio_question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="field">
      <%= f.label :question_text %><br>
      <%= f.text_field :question_text, style: "width:50%;" %>
    </div>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bio_questions/edit.html.erb
<h1>Editing Bio Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @bio_question %> |
<%= link_to 'Back', bio_questions_path %>

app/views/bio_questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bio Questions</h1>
  <p>
    <button>
      <%= link_to 'Create New', new_bio_question_path %>
    </button>
  </p>
  <table class="table table-bordered table-striped" >
    <thead>
      <tr>
        <th>
          Id
        </th>
        <th>
          Question Text
        </th>
        <th>
          Order By (1=TOP)
        </th>
        <th>
          Active?
        </th>
        <th>
          Actions
        </th>
      </tr>
    </thead>
    <tbody>
      <% if @bio_questions.count > 0 %>
        <% @bio_questions.each do |bio_question| %>
          <tr>
            <th>
              <%= bio_question.id %>
            </th>
            <th>
              <%= bio_question.question_text %>
            </th>
            <th>
              <%= bio_question.question_order_by %>
            </th>
            <th>
              <%= bio_question.active %>
            </th>
            <th>
              <%= link_to 'Show', bio_question %>
              <%= link_to 'Edit', edit_bio_question_path(bio_question) %>
              <%= link_to 'Destroy', bio_question, method: :delete, data: { confirm: 'Are you sure?' } %>
            </th>
          </tr> 
        <% end %>
      <% end %>
    </tbody>
  </table>

app/views/bio_questions/new.html.erb
<h1>New Bio Question</h1>

<%= render 'form' %>

<%= link_to 'Back', bio_questions_path %>

app/views/bio_questions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bio_question_path(@bio_question) %> |
<%= link_to 'Back', bio_questions_path %>