config/routes.rb
Rails.application.routes.draw do
  
  resources :companies
  resources :book_resources
  resources :resources
  resources :quotes
  Shrine.plugin :upload_endpoint

  resources :content_fields
  post 'alerts/reply'

  resource :alerts do
    collection do
      post 'reply'
      post 'create_alert'
    end
  end

  resources :images, only: [:new, :create, :index, :edit, :update]
  resources :resource_requests, only: [:create]

  get "/bios/meet_us" => "bios#meet_us"
  
  # resources :notification_preferences
  resources :group_messages
  resources :groups
  resources :group_memberships
  resources :admin_messages
  resources :plans
  resources :mentorships
  resources :messages
  resources :bio_questions
  resources :bio_answers
  resources :bios
  resources :resources
  resources :resource_types
  resources :book_resources
  resources :user_emailer

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'registrations'}

  root to: "dashboard#view"
  mount ImageUploader.upload_endpoint(:cache) => "/images/upload"

  # post "user_emailer/send_book_resources/:email" => "user_emailer"

  post "/assign_company_id/:target_user_id/:company_id" => "dashboard#super_admin_assign_company_id_to_new_user"
  get "company_admin_login/:company_id" => "dashboard#super_admin_log_into_company"

  get "/images/index" => "images#index"

  get "/notification_preferences" => "notification_preferences#index"
  post '/notification_preferences/enable_notification/:reason/:type' => 'notification_preferences#enable_notification'
  post '/notification_preferences/disable_notification/:reason/:type' => 'notification_preferences#disable_notification'

  post '/twilio/voice' => 'twilio#voice'

  get "/alerts/send_email" => "alerts#send_email"
  post "/alerts/send_notifications/:event/:createdModelId" => "alerts#send_notifications"

  get "/landing_page" => "admin_messages#landing_page"
  get "/download_book_resources" => "admin_messages#download_book_resources"
  get "/blog" => "home#blog"
  get "/test" => "home#test"

  get "/user/dashboard" => "dashboard#view"
  get "/user/dashboard/:active_user_id" => "dashboard#view"
  get "/user/group-dashboard" => "dashboard#group_view"
  get "/user/group-dashboard/:active_group_id" => "dashboard#group_view"

  get "/toggle_coach/:target_user_id" => "dashboard#admin_toggle_coach_permissions"
  get "/toggle_admin/:target_user_id" => "dashboard#admin_toggle_admin_permissions"
  get "/toggle_active/:target_user_id" => "dashboard#admin_toggle_active"
  get "/toggle_deleted/:target_user_id" => "dashboard#admin_toggle_deleted"
  get "/activate_user/:target_user_id" => "dashboard#admin_activate_user"

  get "/" => "dashboard#view"


end

app/models/admin_message.rb
class AdminMessage < ActiveRecord::Base
end

app/models/alert.rb
class Alert < ActiveRecord::Base
end

app/models/bio.rb
class Bio < ActiveRecord::Base
end

app/models/bio_answer.rb
class BioAnswer < ActiveRecord::Base
end

app/models/bio_question.rb
class BioQuestion < ActiveRecord::Base
end

app/models/book_resource.rb
class BookResource < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/content_field.rb
class ContentField < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base

	require "shrine/storage/s3"

	# adds an `image` virtual attribute
	include ImageUploader::Attachment.new(:image)

end

app/models/mentorship.rb
class Mentorship < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/resource_type.rb
class ResourceType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # before_save :set_default_permissions
  scope :ordered_by_name, -> { order(first_name: :asc) }

  def full_name
    "#{first_name} #{last_name}"
  end

   def set_default_permissions

    # TODO: needs debugging:
      self.is_a_coach = false
      self.is_an_admin = false
      self.is_super_admin = false
   end    
  
  # ensure user account is active  
  def active_for_authentication?  
    self.is_active  
  end  
  
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>
      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div style="color:red;">Resource Type IDs are below:
    <br />2 - Link
    <br />3 - File
    <br />4 - Note
    <br />5 - Image
    <br />
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div style="color:red;">
    Note: If this is a link or a file, you will need to use the ENTIRE url below (example: Use "http://www.google.com/" instead of just "Google") for it to be displayed and to function properly throughout the site.
  </div>
  <div class="field">
    <%= f.label :resource_string %><br>
    <%= f.text_area :resource_string %>
  </div>
  <div class="field">
    <%= f.label :resource_type_id %><br>
    <%= f.number_field :resource_type_id %>
  </div>
  <div class="field">
    <%= f.label :tag_1 %><br>
    <%= f.text_field :tag_1 %>
  </div>
  <div class="field">
    <%= f.label :tag_2 %><br>
    <%= f.text_field :tag_2 %>
  </div>
  <div class="field">
    <%= f.label :tag_3 %><br>
    <%= f.text_field :tag_3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>
<div style="color:red">This will be enhanced to include create, edit, view capabilities for coaches. For now, this is an admin-only area. The Resource Type IDs are below:
  <br />2 - Link
  <br />3 - File
  <br />4 - Note
  <br />5 - Image
</div>
<hr>
<p>
  <button>
    <%= link_to 'New Resource', new_resource_path %>
  </button>
</p>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Resource string</th>
      <th>Resource type</th>
      <th>Tag 1</th>
      <th>Tag 2</th>
      <th>Tag 3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.title %></td>
        <td><%= resource.description %></td>
        <td><%= resource.resource_string %></td>
        <td><%= resource.resource_type_id %></td>
        <td><%= resource.tag_1 %></td>
        <td><%= resource.tag_2 %></td>
        <td><%= resource.tag_3 %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>Resource string:</strong>
  <%= @resource.resource_string %>
</p>

<p>
  <strong>Resource type:</strong>
  <%= @resource.resource_type_id %>
</p>

<p>
  <strong>Tag 1:</strong>
  <%= @resource.tag_1 %>
</p>

<p>
  <strong>Tag 2:</strong>
  <%= @resource.tag_2 %>
</p>

<p>
  <strong>Tag 3:</strong>
  <%= @resource.tag_3 %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>