config/routes.rb
Rails.application.routes.draw do
  
  resources :companies
  resources :book_resources
  resources :resources
  resources :quotes
  Shrine.plugin :upload_endpoint

  resources :content_fields
  post 'alerts/reply'

  resource :alerts do
    collection do
      post 'reply'
      post 'create_alert'
    end
  end

  resources :images, only: [:new, :create, :index, :edit, :update]
  resources :resource_requests, only: [:create]

  get "/bios/meet_us" => "bios#meet_us"
  
  # resources :notification_preferences
  resources :group_messages
  resources :groups
  resources :group_memberships
  resources :admin_messages
  resources :plans
  resources :mentorships
  resources :messages
  resources :bio_questions
  resources :bio_answers
  resources :bios
  resources :resources
  resources :resource_types
  resources :book_resources
  resources :user_emailer

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'registrations'}

  root to: "dashboard#view"
  mount ImageUploader.upload_endpoint(:cache) => "/images/upload"

  # post "user_emailer/send_book_resources/:email" => "user_emailer"

  post "/assign_company_id/:target_user_id/:company_id" => "dashboard#super_admin_assign_company_id_to_new_user"
  get "company_admin_login/:company_id" => "dashboard#super_admin_log_into_company"

  get "/images/index" => "images#index"

  get "/notification_preferences" => "notification_preferences#index"
  post '/notification_preferences/enable_notification/:reason/:type' => 'notification_preferences#enable_notification'
  post '/notification_preferences/disable_notification/:reason/:type' => 'notification_preferences#disable_notification'

  post '/twilio/voice' => 'twilio#voice'

  get "/alerts/send_email" => "alerts#send_email"
  post "/alerts/send_notifications/:event/:createdModelId" => "alerts#send_notifications"

  get "/landing_page" => "admin_messages#landing_page"
  get "/download_book_resources" => "admin_messages#download_book_resources"
  get "/blog" => "home#blog"
  get "/test" => "home#test"

  get "/user/dashboard" => "dashboard#view"
  get "/user/dashboard/:active_user_id" => "dashboard#view"
  get "/user/group-dashboard" => "dashboard#group_view"
  get "/user/group-dashboard/:active_group_id" => "dashboard#group_view"

  get "/toggle_coach/:target_user_id" => "dashboard#admin_toggle_coach_permissions"
  get "/toggle_admin/:target_user_id" => "dashboard#admin_toggle_admin_permissions"
  get "/toggle_active/:target_user_id" => "dashboard#admin_toggle_active"
  get "/toggle_deleted/:target_user_id" => "dashboard#admin_toggle_deleted"
  get "/activate_user/:target_user_id" => "dashboard#admin_activate_user"

  get "/" => "dashboard#view"


end

app/models/admin_message.rb
class AdminMessage < ActiveRecord::Base
end

app/models/alert.rb
class Alert < ActiveRecord::Base
end

app/models/bio.rb
class Bio < ActiveRecord::Base
end

app/models/bio_answer.rb
class BioAnswer < ActiveRecord::Base
end

app/models/bio_question.rb
class BioQuestion < ActiveRecord::Base
end

app/models/book_resource.rb
class BookResource < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/content_field.rb
class ContentField < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base

	require "shrine/storage/s3"

	# adds an `image` virtual attribute
	include ImageUploader::Attachment.new(:image)

end

app/models/mentorship.rb
class Mentorship < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/resource_type.rb
class ResourceType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # before_save :set_default_permissions
  scope :ordered_by_name, -> { order(first_name: :asc) }

  def full_name
    "#{first_name} #{last_name}"
  end

   def set_default_permissions

    # TODO: needs debugging:
      self.is_a_coach = false
      self.is_an_admin = false
      self.is_super_admin = false
   end    
  
  # ensure user account is active  
  def active_for_authentication?  
    self.is_active  
  end  
  
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :find_mentorship

  before_filter :authorized_user, only: [:edit, :update, :show, :destroy]
  before_filter :admin_user, only: [:index]
  layout "signed-in"

  # GET /plans
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit

  end

  # POST /plans
  def create
    @plan = Plan.new(plan_params)
    if current_user.is_an_admin = false && current_user.is_a_coach = false
      @plan.client = current_user.id
    end
    if @plan.save

        id = @plan.id
        alerts = AlertsController.new
        alerts.request = request
        alerts.response = response
        alerts.send_notifications("plan_created", id)
      
      redirect_to "/user/dashboard", notice: 'Plan was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /plans/1
  def update
    if @plan.update(plan_params)

      id = @plan.id
        alerts = AlertsController.new
        alerts.request = request
        alerts.response = response
        alerts.send_notifications("plan_created", id)
      
      redirect_to "/user/dashboard", notice: 'Plan was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /plans/1
  def destroy
    # render :text => 'fsdfsdfs<%= sign_in_params %>'
    @plan.destroy
    redirect_to "/user/dashboard/", notice: 'Plan was successfully destroyed.'
  end

  protected 

  def authorized_user
    if (@plan.client == current_user.id)

    elsif @mentorship.present?
      redirect_to "/" unless @plan.client == current_user.id || @clientsIds.include?(@plan.client) 

    elsif @coach_mentorships.present?

      @clients_of_coach = []

      @coach_mentorships.each do |m|

        @clients_of_coach << m.client

    end

      redirect_to "/" unless @clients_of_coach.include?(@plan.client)
      
    else redirect_to "/" unless current_user.is_an_admin?
    end

  end

  def admin_user
    # Is the current user an admin? If not, user is redirected to their dashboard. 
    redirect_to "/" unless current_user.is_an_admin == true
  end

# ////////////////////////////////

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    def find_mentorship
      if current_user.is_a_coach? == false && current_user.is_an_admin? == false
        @mentorship = Mentorship.find_by(client: current_user.id)
      elsif current_user.is_a_coach? && current_user.is_an_admin? == false
        @coach_mentorships = Mentorship.where(coach: current_user.id)
      end
    end

    # Only allow a trusted parameter "white list" through.
    def plan_params
      params.require(:plan).permit(:client, :title, :content)
    end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/plans/_form.html.erb
<!--<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hide-this">
    <div class="field">
      <% if current_user.is_a_coach? || current_user.is_an_admin? %>
        <%= f.number_field :client, :value => @active_user_id %>
      <% else %>
        <%= f.number_field :client, :value => @current_user.id %>
      <% end %>  
    </div>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <br>
  
    <%= f.label :content %><br>
    
    <%= f.text_area :content, class:"textarea_editor form-control" %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>-->


<%= form_for(@plan) do |f| %>
<div class="col-xlg-12 col-lg-12 col-md-12 bg-light border-left">
      <div class="card-body">
  <% if @plan.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="hide-this">
    <div class="form-group">
      <% if current_user.is_a_coach? || current_user.is_an_admin? %>
        <%= f.number_field :client, :value => @active_user_id %>
      <% else %>
        <%= f.number_field :client, :value => @current_user.id %>
      <% end %>  
    </div>
  </div>

      <div class="form-group">
             <%= f.label :title %><br>
             <%= f.text_field :title, class:"form-control" %>
      </div>
       <div class="form-group">
        <%= f.label :content %><br>
        <%= f.text_area :content, class:"textarea_editor form-control", rows:"15"   %>
        </div>
        <div class="actions">
          <%= f.submit 'Create plan', :class => 'btn btn-success' %>
        </div>
    </div>
  </div>

<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
  <div class="card col-10  pull-right"  style="margin-top: 100px;">
        <div class="card-body">
            <p id="notice"><%= notice %></p>
            <h4 class="card-title">Plans</h4>
            <!-- <h6 class="card-subtitle">Data table example</h6> -->
            <button style="padding: 0;">
              <%= link_to 'New Plan', new_plan_path, class: "btn btn-success" %>
            </button>
            <div class="table-responsive m-t-40">
                <table id="myTable" class="table table-bordered table-striped">
                     <thead>
                      <tr>
                        <th>
                          Id
                        </th> 
                        <th>
                          Client
                        </th>
                        <th>
                          Title
                        </th>
                        <th>
                          Content
                        </th>
                        <th>
                          Actions
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <% if @plans != nil %>
                        <% @plans.each do |plan| %>
                          <tr>
                            <th>
                              <%= plan.id %>
                            </th>
                            <th>
                              <%= plan.client %>
                            </th>
                            <th>
                              <%= plan.title %>
                            </th>
                            <th>
                              <%= plan.content %>
                            </th>
                            <th>
                              <%= link_to 'Show', plan %>

                              <%= link_to 'Edit', edit_plan_path(plan) %>

                              <%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %>
                            </th>
                          </tr> 
                        <% end %>
                      <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


<!-- <p id="notice"><%= notice %></p>

<h1>Plans</h1>
<p>
    <button>
      <%= link_to 'New Plan', new_plan_path %>
    </button>
  </p>
<table class="table table-bordered table-striped" >
    <thead>
      <tr>
        <th>
          Id
        </th> 
        <th>
          Client
        </th>
        <th>
          Title
        </th>
        <th>
          Content
        </th>
        <th>
          Actions
        </th>
      </tr>
    </thead>
    <tbody>
      <% if @plans != nil %>
        <% @plans.each do |plan| %>
          <tr>
            <th>
              <%= plan.id %>
            </th>
            <th>
              <%= plan.client %>
            </th>
            <th>
              <%= plan.title %>
            </th>
            <th>
              <%= plan.content %>
            </th>
            <th>
              <%= link_to 'Show', plan %>

              <%= link_to 'Edit', edit_plan_path(plan) %>

              <%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %>
            </th>
          </tr> 
        <% end %>
      <% end %>
    </tbody>
  </table> -->

app/views/plans/new.html.erb
<%= render "plans/form" %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @plan.client %>
</p>

<p>
  <strong>Title:</strong>
  <%= @plan.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @plan.content %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>